### ISSUE TITLE
todo project management

### ISSUE THREAD

**Issue by Ab2nour** [jExbrayat/projet-m2-ML#10]
# CI
## Code
- [x] add flake8 to lint code (and its plugins below)
  - [x] flake8-bugbear
  - [x] pandas-vet
  - [x] flake8-annotations
- [x] run isort on _check mode_
- [x] #5 

## Notebook-specific
- [x] add nb-clean (to check for unnecessary metadata and empty cells in notebooks)
- [x] add nbqa to run isort & flake8 on notebooks as well

**Comment by Ab2nour** [comment]
@jExbrayat, since you are the owner of the project, you should be the one setting up all these automations. Feel free to inspire you from https://github.com/Ab2nour/stock-analysis from example.

**Comment by jExbrayat** [comment]
Flake8 and nb-clean have been added as steps for github actions.
Isort now checks notebooks.
